version: '3.8'

services:
  mint:
    image: mint
    container_name: mint
    build: .
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4

volumes:
  redis_data: